### PR TITLE
fix: skip disabled pups cleanly during nix rebuilds

### LINKED ISSUE #205: Nix rebuild fails when a pup has been stopped
When an installed pup is intentionally disabled, subsequent Nix rebuilds are looking like they failed.
The pup container's `ExecCondition` calls `dbx can-pup-start`, and for a disabled pup that was returning a systemd error instead of a normal "don't start this" condition.
This caused systemd to mark the unit as failed, which then bubbled up to `nixos-rebuild switch` erroring.

```
[2026-04-02 16:16:15] Queued, position 0
[2026-04-02 16:16:15] Validating custom nix configuration...
[2026-04-02 16:16:15] Validation passed, saving configuration...
[2026-04-02 16:16:15] Ensuring dogebox.nix includes custom.nix...
[2026-04-02 16:16:15] custom.nix import already exists in dogebox.nix
[2026-04-02 16:16:15] Triggering system rebuild...
[2026-04-02 16:16:15] 2026/04/02 16:16:15 ----------------------------------------
[2026-04-02 16:16:15] aarch64
[2026-04-02 16:16:15] 2026/04/02 16:16:15 Running command: [uname -m]
[2026-04-02 16:16:15] 2026/04/02 16:16:15 ----------------------------------------
[2026-04-02 16:16:15] warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
[2026-04-02 16:16:15] building the system configuration...
[2026-04-02 16:16:16] warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
[2026-04-02 16:16:21] this derivation will be built:
[2026-04-02 16:16:21] /nix/store/1hf7mvx054cxdvfwj1kyksr522zpjsxr-nixos-system-my-dogebox-755-25.11.20260329.107cba9.drv
[2026-04-02 16:16:21] building '/nix/store/1hf7mvx054cxdvfwj1kyksr522zpjsxr-nixos-system-my-dogebox-755-25.11.20260329.107cba9.drv'...
[2026-04-02 16:16:21] activating the configuration...
[2026-04-02 16:16:21] setting up /etc...
[2026-04-02 16:16:21] restarting sysinit-reactivation.target
[2026-04-02 16:16:30] warning: the following units failed: container@pup-dc0f22925b1aa6093d531b599c73074f.service
[2026-04-02 16:16:30] × container@pup-dc0f22925b1aa6093d531b599c73074f.service - Container 'pup-dc0f22925b1aa6093d531b599c73074f'
[2026-04-02 16:16:30] Loaded: loaded (/etc/systemd/system/container@pup-dc0f22925b1aa6093d531b599c73074f.service; linked; preset: ignored)
[2026-04-02 16:16:30] Active: failed (Result: exit-code) since Thu 2026-04-02 16:16:23 AEDT; 6s ago
[2026-04-02 16:16:30] Duration: 8min 12.328s
[2026-04-02 16:16:30] Command 'systemd-run -E LOCALE_ARCHIVE -E NIXOS_INSTALL_BOOTLOADER --collect --no-ask-password --pipe --quiet --service-type=exec --unit=nixos-rebuild-switch-to-configuration /nix/store/m2rzh88i3bz1rfy3zb8xcc5wnqb0p4vw-nixos-system-my-dogebox-755-25.11.20260329.107cba9/bin/switch-to-configuration switch' returned non-zero exit status 4.
[2026-04-02 16:16:30] Invocation: 4d55a39896bb4781a23c72abe487f979
[2026-04-02 16:16:30] Process: 65742 ExecCondition=/run/wrappers/bin/dbx can-pup-start --data-dir /opt/dogebox --systemd --pup-id dc0f22925b1aa6093d531b599c73074f (code=exited, status=255/EXCEPTION)
[2026-04-02 16:16:30] Error executing nixos-rebuild switch: exit status 4
[2026-04-02 16:16:30] IP: 0B in, 0B out
[2026-04-02 16:16:30] IO: 0B read, 0B written
[2026-04-02 16:16:30] Mem peak: 4.3M
[2026-04-02 16:16:30] CPU: 22ms
[2026-04-02 16:16:30]
[2026-04-02 16:16:30] Apr 02 16:16:23 my-dogebox-755 systemd[1]: container@pup-dc0f22925b1aa6093d531b599c73074f.service: Scheduled restart job, restart counter is at 5.
[2026-04-02 16:16:30] Apr 02 16:16:23 my-dogebox-755 systemd[1]: container@pup-dc0f22925b1aa6093d531b599c73074f.service: Start request repeated too quickly.
[2026-04-02 16:16:30] Apr 02 16:16:23 my-dogebox-755 systemd[1]: container@pup-dc0f22925b1aa6093d531b599c73074f.service: Failed with result 'exit-code'.
[2026-04-02 16:16:30] Apr 02 16:16:23 my-dogebox-755 systemd[1]: Failed to start Container 'pup-dc0f22925b1aa6093d531b599c73074f'.
[2026-04-02 16:16:30] Error executing nix rebuild: exit status 1
[2026-04-02 16:16:30] Rebuild failed: exit status 1
[2026-04-02 16:16:30] finished in 15.04s, queued 15.15s
[2026-04-02 16:16:30] Failed to save custom configuration
```

### PR DESCRIPTION
**Pull request by elusiveshiba**
Treat disabled pups as a normal ExecCondition miss instead of a systemd error so rebuilds are not marked as failed

See issue for more details: https://github.com/Dogebox-WG/dogeboxd/issues/205

### CODE REVIEW

File: cmd/dbx/cmd/can-pup-start.go [hunk 1]
```diff
@@ -84,15 +84,19 @@ var canPupStartCmd = &cobra.Command{
...
 		}
 
-		log.Println("Can start: false")
-		utils.ExitBad(systemd)
+		if pupState, ok := pupManager.GetStateMap()[pupId]; ok && !pupState.Enabled {
+			log.Println("Can start: false (pup is disabled)")
+		} else {
+			log.Println("Can start: false")
+		}
+		utils.ExitConditionNotMet(systemd)
```
Comment (DivineGod) [inline cmd/dbx/cmd/can-pup-start.go]:
```suggestion
		os.Exit(1) // Normal exit error status
```

File: cmd/dbx/utils/utils.go [hunk 2]
```diff
@@ -10,3 +10,7 @@ func ExitBad(isSystemd bool) {
 
 	os.Exit(1)
 }
+
+func ExitConditionNotMet(_ bool) {
+	os.Exit(1)
+}
```
Comment (DivineGod) [inline cmd/dbx/utils/utils.go]:
```suggestion
```

This is superfluous. Remove

**Review by DivineGod — CHANGES_REQUESTED** [review]
We should probably just use `os.Exit(1)` directly, or re-use `utils.exitBad(false)` instead. 

Don't need to over-complicate things with a function that even has the wrong signature.

**Comment by elusiveshiba** [comment]
Fair call @DivineGod I've updated that now

**Review by DivineGod — APPROVED** [review]
